1.
SELECT S.*, SS.SEM, SS.SEC 
FROM STUDENT S, SEMSEC SS, CLASS C
WHERE S.USN = C.USN AND 
SS.SSID = C.SSID AND
SS.SEM = 4 AND
SS.SEC=’C’;

2.
    SELECT SS.SEM, SS.SEC, S.GENDER, COUNT (S.GENDER) AS COUNT 
FROM STUDENT1 S, SEMSEC SS, CLASS C 
WHERES.USN = C.USN AND
SS.SSID = C.SSID
GROUP BY SS.SEM, SS.SEC, S.GENDER
ORDER BY SEM;

3.
CREATE VIEW STU_TEST1_MARKS_VIEW AS
SELECT TEST1, SUBCODE
FROM IAMARKS 
WHERE USN = '1RN13CS091';

4.
    UPDATE IAMARKS
SET FINALIA = (CASE 
        WHEN GREATEST(TEST1, TEST2) <> GREATEST(TEST1, TEST3)
        THEN (GREATEST(TEST1, TEST2) + GREATEST(TEST1, TEST3))
        ELSE (GREATEST(TEST1, TEST2) + GREATEST(TEST2, TEST3))
    END) / 2
WHERE FINALIA IS NULL;

            OR

update imarks m
set finalia=(select sum((t1+t2+t3-least (t1,t2,t3))/2)
from iamarks m2
where m2.usn=m.usn
and m2.sub_code=m.sub_code);

5.
SELECT S.USN,S.SNAME,S.ADDRESS,S.PHONE,S.GENDER,
 (CASE 
 WHEN IA.FINALIA BETWEEN 17 AND 20 THEN 'OUTSTANDING'
 WHEN IA.FINALIA BETWEEN 12 AND 16 THEN 'AVERAGE'
 ELSE 'WEAK'
 END) AS CAT
FROM STUDENT S, SEMSEC SS, IAMARKS IA, SUBJECT SUB
WHERE S.USN = IA.USN AND 
SS.SSID = IA.SSID AND
SUB.SUBCODE = IA.SUBCODE AND
SUB.SEM = 8;

